In [2]:
import numpy as np
import pandas as pd

In [5]:
## Dummy data
ID=np.arange(1,51)
table_column=["CA1","CA2","CA3"]
np.random.seed(1)
score=np.random.randint(1,11,150)
score= score.reshape(50,3)
data=pd.DataFrame(data=score,index=ID,columns=table_column)
data.tail()

CA1  CA2  CA3
46    1    7    6
47    2    3    2
48    6    5    1
49    8    9   10
50    6    8    1

In [4]:
data["CA3"]

1     10
2      1
3      7
4      5
5      5
6      8
7      2
8      7
9      8
10     2
11     9
12    10
13     4
14     2
15     5
16     5
17    10
18     5
19     8
20     9
21     4
22     5
23     4
24     1
25     8
26     4
27     8
28     2
29     9
30     6
31     6
32     5
33     8
34     1
35     8
36    10
37     1
38     9
39     2
40     3
41    10
42     7
43     8
44     6
45     7
46     6
47     2
48     1
49    10
50     1
Name: CA3, dtype: int32

In [5]:
data[["CA1","CA3"]] ## SELECTING COLUMNS.

CA1  CA3
1     6   10
2     6    1
3     2    7
4    10    5
5     6    5
6     3    8
7     8    2
8     8    7
9    10    8
10    7    2
11    1    9
12    9   10
13    9    4
14    7    2
15   10    5
16    9    5
17    1   10
18    3    5
19   10    8
20    8    9
21    7    4
22    8    5
23    6    4
24    7    1
25    3    8
26   10    4
27    1    8
28    8    2
29    4    9
30    7    6
31    7    6
32    8    5
33    5    8
34    5    1
35    3    8
36    2   10
37    9    1
38    2    9
39    3    2
40    3    3
41    7   10
42    3    7
43    3    8
44    1    6
45    2    7
46    1    6
47    2    2
48    6    1
49    8   10
50    6    1

In [7]:
data.loc[50] ## Selecting a single index or row with set index

CA1    6
CA2    8
CA3    1
Name: 50, dtype: int32

In [8]:
data.iloc[6] ## selecting a single index or row with default index

CA1     8
CA2    10
CA3     2
Name: 7, dtype: int32

In [9]:
data.loc[[45,46,47,48,49,50]] ## selecting more than a row or index based on set index.

CA1  CA2  CA3
45    2    5    7
46    1    7    6
47    2    3    2
48    6    5    1
49    8    9   10
50    6    8    1

In [13]:
np.random.seed(2)
age= np.random.randint(11,18,50).reshape(50,1)
data.insert(loc=4,value=age,column="AGE2")
data

AGE  CA1  CA2  CA3  AGE2
1    11    6    9   10    11
2    16    6    1    1    16
3    11    2    8    7    11
4    17   10    3    5    17
5    14    6    3    5    14
6    13    3    5    8    13
7    14    8   10    2    14
8    11    8    1    7    11
9    13   10   10    8    13
10   12    7   10    2    12
11   14    1    2    9    14
12   16    9    4   10    16
13   13    9    8    4    13
14   15    7    6    2    15
15   15   10    4    5    15
16   15    9    2    5    15
17   16    1    4   10    16
18   14    3    1    5    14
19   17   10    3    8    17
20   15    8   10    9    15
21   13    7   10    4    13
22   14    8    8    5    14
23   14    6   10    4    14
24   17    7    9    1    17
25   13    3    8    8    13
26   12   10    8    4    12
27   13    1    9    8    13
28   15    8    2    2    15
29   14    4    1    9    14
30   16    7    5    6    16
31   11    7    3    6    11
32   15    8    9    5    15
33   17    5    8    8    17
34   17    5   10    1    17
35   14    3    1    8    14
36   12    2    8   10    12
37   13    9    5    1    13
38   11    2   10    9    11
39   15    3    4    2    15
40   17    3    8    3    17
41   15    7    1   10    15
42   13    3    7    7    13
43   15    3    8    8    15
44   13    1    7    6    13
45   12    2    5    7    12
46   17    1    7    6    17
47   11    2    3    2    11
48   13    6    5    1    13
49   16    8    9   10    16
50   13    6    8    1    13

In [14]:
np.random.seed(1)
data["EXAM"]=np.random.randint(20,80,50).reshape(50,1)
data

AGE  CA1  CA2  CA3  AGE2  EXAM
1    11    6    9   10    11    57
2    16    6    1    1    16    63
3    11    2    8    7    11    32
4    17   10    3    5    17    28
5    14    6    3    5    14    29
6    13    3    5    8    13    31
7    14    8   10    2    14    25
8    11    8    1    7    11    35
9    13   10   10    8    13    20
10   12    7   10    2    12    36
11   14    1    2    9    14    21
12   16    9    4   10    16    32
13   13    9    8    4    13    27
14   15    7    6    2    15    65
15   15   10    4    5    15    26
16   15    9    2    5    15    45
17   16    1    4   10    16    70
18   14    3    1    5    14    40
19   17   10    3    8    17    57
20   15    8   10    9    15    38
21   13    7   10    4    13    40
22   14    8    8    5    14    31
23   14    6   10    4    14    62
24   17    7    9    1    17    48
25   13    3    8    8    13    49
26   12   10    8    4    12    34
27   13    1    9    8    13    70
28   15    8    2    2    15    24
29   14    4    1    9    14    43
30   16    7    5    6    16    43
31   11    7    3    6    11    61
32   15    8    9    5    15    69
33   17    5    8    8    17    75
34   17    5   10    1    17    50
35   14    3    1    8    14    52
36   12    2    8   10    12    42
37   13    9    5    1    13    33
38   11    2   10    9    11    61
39   15    3    4    2    15    29
40   17    3    8    3    17    27
41   15    7    1   10    15    42
42   13    3    7    7    13    77
43   15    3    8    8    15    21
44   13    1    7    6    13    20
45   12    2    5    7    12    37
46   17    1    7    6    17    28
47   11    2    3    2    11    44
48   13    6    5    1    13    33
49   16    8    9   10    16    71
50   13    6    8    1    13    67

In [15]:
data["TotalScore"]=data["CA1"] + data["CA2"] + data["CA3"] + data["EXAM"]
data

AGE  CA1  CA2  CA3  AGE2  EXAM  TotalScore
1    11    6    9   10    11    57          82
2    16    6    1    1    16    63          71
3    11    2    8    7    11    32          49
4    17   10    3    5    17    28          46
5    14    6    3    5    14    29          43
6    13    3    5    8    13    31          47
7    14    8   10    2    14    25          45
8    11    8    1    7    11    35          51
9    13   10   10    8    13    20          48
10   12    7   10    2    12    36          55
11   14    1    2    9    14    21          33
12   16    9    4   10    16    32          55
13   13    9    8    4    13    27          48
14   15    7    6    2    15    65          80
15   15   10    4    5    15    26          45
16   15    9    2    5    15    45          61
17   16    1    4   10    16    70          85
18   14    3    1    5    14    40          49
19   17   10    3    8    17    57          78
20   15    8   10    9    15    38          65
21   13    7   10    4    13    40          61
22   14    8    8    5    14    31          52
23   14    6   10    4    14    62          82
24   17    7    9    1    17    48          65
25   13    3    8    8    13    49          68
26   12   10    8    4    12    34          56
27   13    1    9    8    13    70          88
28   15    8    2    2    15    24          36
29   14    4    1    9    14    43          57
30   16    7    5    6    16    43          61
31   11    7    3    6    11    61          77
32   15    8    9    5    15    69          91
33   17    5    8    8    17    75          96
34   17    5   10    1    17    50          66
35   14    3    1    8    14    52          64
36   12    2    8   10    12    42          62
37   13    9    5    1    13    33          48
38   11    2   10    9    11    61          82
39   15    3    4    2    15    29          38
40   17    3    8    3    17    27          41
41   15    7    1   10    15    42          60
42   13    3    7    7    13    77          94
43   15    3    8    8    15    21          40
44   13    1    7    6    13    20          34
45   12    2    5    7    12    37          51
46   17    1    7    6    17    28          42
47   11    2    3    2    11    44          51
48   13    6    5    1    13    33          45
49   16    8    9   10    16    71          98
50   13    6    8    1    13    67          82

In [16]:
data.columns

Index(['AGE', 'CA1', 'CA2', 'CA3', 'AGE2', 'EXAM', 'TotalScore'], dtype='object')

In [17]:
for x in data.columns:
    print(data[x].unique())

[11 16 17 14 13 12 15]
[ 6  2 10  3  8  7  1  9  4  5]
[ 9  1  8  3  5 10  2  4  6  7]
[10  1  7  5  8  2  9  4  6  3]
[11 16 17 14 13 12 15]
[57 63 32 28 29 31 25 35 20 36 21 27 65 26 45 70 40 38 62 48 49 34 24 43
 61 69 75 50 52 42 33 77 37 44 71 67]
[82 71 49 46 43 47 45 51 48 55 33 80 61 85 78 65 52 68 56 88 36 57 77 91
 96 66 64 62 38 41 60 94 40 34 42 98]


In [18]:
for x in data.columns:
    print(data[x].nunique())

7
10
10
10
7
36
36


In [19]:
for x in data.columns:
    print(data[x].value_counts())

AGE
13    11
15     9
14     8
17     7
11     6
16     5
12     4
Name: count, dtype: int64
CA1
3     8
8     7
7     7
6     6
2     5
10    5
1     5
9     4
5     2
4     1
Name: count, dtype: int64
CA2
8     10
10     8
1      6
9      5
3      5
5      5
4      4
2      3
7      3
6      1
Name: count, dtype: int64
CA3
8     8
5     7
10    6
1     6
2     6
7     4
9     4
4     4
6     4
3     1
Name: count, dtype: int64
AGE2
13    11
15     9
14     8
17     7
11     6
16     5
12     4
Name: count, dtype: int64
EXAM
57    2
20    2
40    2
70    2
42    2
33    2
43    2
21    2
27    2
31    2
29    2
28    2
32    2
61    2
37    1
44    1
71    1
77    1
52    1
50    1
75    1
69    1
62    1
24    1
34    1
49    1
48    1
63    1
38    1
45    1
26    1
65    1
36    1
35    1
25    1
67    1
Name: count, dtype: int64
TotalScore
82    4
45    3
51    3
48    3
61    3
49    2
55    2
65    2
38    1
96    1
66    1
64    1
62    1
94    1
41    1
60    1
77    1
40    1

In [22]:
data.rename({"EXAM":"Exams"},axis=1,inplace=True) ## Rename a column
data

AGE  CA1  CA2  CA3  AGE2  Exams  TotalScore
1    11    6    9   10    11     57          82
2    16    6    1    1    16     63          71
3    11    2    8    7    11     32          49
4    17   10    3    5    17     28          46
5    14    6    3    5    14     29          43
6    13    3    5    8    13     31          47
7    14    8   10    2    14     25          45
8    11    8    1    7    11     35          51
9    13   10   10    8    13     20          48
10   12    7   10    2    12     36          55
11   14    1    2    9    14     21          33
12   16    9    4   10    16     32          55
13   13    9    8    4    13     27          48
14   15    7    6    2    15     65          80
15   15   10    4    5    15     26          45
16   15    9    2    5    15     45          61
17   16    1    4   10    16     70          85
18   14    3    1    5    14     40          49
19   17   10    3    8    17     57          78
20   15    8   10    9    15     38          65
21   13    7   10    4    13     40          61
22   14    8    8    5    14     31          52
23   14    6   10    4    14     62          82
24   17    7    9    1    17     48          65
25   13    3    8    8    13     49          68
26   12   10    8    4    12     34          56
27   13    1    9    8    13     70          88
28   15    8    2    2    15     24          36
29   14    4    1    9    14     43          57
30   16    7    5    6    16     43          61
31   11    7    3    6    11     61          77
32   15    8    9    5    15     69          91
33   17    5    8    8    17     75          96
34   17    5   10    1    17     50          66
35   14    3    1    8    14     52          64
36   12    2    8   10    12     42          62
37   13    9    5    1    13     33          48
38   11    2   10    9    11     61          82
39   15    3    4    2    15     29          38
40   17    3    8    3    17     27          41
41   15    7    1   10    15     42          60
42   13    3    7    7    13     77          94
43   15    3    8    8    15     21          40
44   13    1    7    6    13     20          34
45   12    2    5    7    12     37          51
46   17    1    7    6    17     28          42
47   11    2    3    2    11     44          51
48   13    6    5    1    13     33          45
49   16    8    9   10    16     71          98
50   13    6    8    1    13     67          82

In [23]:
data.drop(columns=["AGE2"],axis=1,inplace=True)
data

AGE  CA1  CA2  CA3  Exams  TotalScore
1    11    6    9   10     57          82
2    16    6    1    1     63          71
3    11    2    8    7     32          49
4    17   10    3    5     28          46
5    14    6    3    5     29          43
6    13    3    5    8     31          47
7    14    8   10    2     25          45
8    11    8    1    7     35          51
9    13   10   10    8     20          48
10   12    7   10    2     36          55
11   14    1    2    9     21          33
12   16    9    4   10     32          55
13   13    9    8    4     27          48
14   15    7    6    2     65          80
15   15   10    4    5     26          45
16   15    9    2    5     45          61
17   16    1    4   10     70          85
18   14    3    1    5     40          49
19   17   10    3    8     57          78
20   15    8   10    9     38          65
21   13    7   10    4     40          61
22   14    8    8    5     31          52
23   14    6   10    4     62          82
24   17    7    9    1     48          65
25   13    3    8    8     49          68
26   12   10    8    4     34          56
27   13    1    9    8     70          88
28   15    8    2    2     24          36
29   14    4    1    9     43          57
30   16    7    5    6     43          61
31   11    7    3    6     61          77
32   15    8    9    5     69          91
33   17    5    8    8     75          96
34   17    5   10    1     50          66
35   14    3    1    8     52          64
36   12    2    8   10     42          62
37   13    9    5    1     33          48
38   11    2   10    9     61          82
39   15    3    4    2     29          38
40   17    3    8    3     27          41
41   15    7    1   10     42          60
42   13    3    7    7     77          94
43   15    3    8    8     21          40
44   13    1    7    6     20          34
45   12    2    5    7     37          51
46   17    1    7    6     28          42
47   11    2    3    2     44          51
48   13    6    5    1     33          45
49   16    8    9   10     71          98
50   13    6    8    1     67          82