## Numpy

In [1]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
arr1=np.array([84,58,96,36])

In [5]:
arr1

array([84, 58, 96, 36])

In [6]:
arr1.ndim
## this what we use to check the dimnension of an array.

1

In [7]:
arr1.shape
## this just give the value inside the array

(4,)

In [8]:
arr2= np.array([[87,45,78,50],[45,78,96,35]],dtype=int)
arr2

array([[87, 45, 78, 50],
       [45, 78, 96, 35]])

In [9]:
arr2.ndim

2

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr2.shape

(2, 4)

In [12]:
np.linspace(14,50)

array([14.        , 14.73469388, 15.46938776, 16.20408163, 16.93877551,
       17.67346939, 18.40816327, 19.14285714, 19.87755102, 20.6122449 ,
       21.34693878, 22.08163265, 22.81632653, 23.55102041, 24.28571429,
       25.02040816, 25.75510204, 26.48979592, 27.2244898 , 27.95918367,
       28.69387755, 29.42857143, 30.16326531, 30.89795918, 31.63265306,
       32.36734694, 33.10204082, 33.83673469, 34.57142857, 35.30612245,
       36.04081633, 36.7755102 , 37.51020408, 38.24489796, 38.97959184,
       39.71428571, 40.44897959, 41.18367347, 41.91836735, 42.65306122,
       43.3877551 , 44.12244898, 44.85714286, 45.59183673, 46.32653061,
       47.06122449, 47.79591837, 48.53061224, 49.26530612, 50.        ])

In [14]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [16]:
np.ones(20) + 5

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6.])

In [17]:
np.zeros(15) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [18]:
arr3= np.arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
arr3= np.arange(1,101,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [2]:
np.random.seed(1)
arr4=np.random.randint(15,100,100)
arr4

array([52, 27, 87, 24, 90, 20, 94, 79, 31, 16, 91, 86, 21, 40, 65, 35, 33,
       99, 26, 43, 44, 29, 65, 83, 28, 24, 22, 78, 76, 37, 72, 16, 15, 75,
       96, 23, 28, 62, 87, 45, 86, 18, 85, 36, 64, 72, 18, 83, 39, 58, 91,
       41, 67, 95, 56, 97, 30, 79, 83, 40, 22, 41, 40, 37, 24, 82, 38, 42,
       52, 72, 98, 53, 23, 47, 49, 25, 38, 30, 40, 86, 89, 77, 61, 47, 38,
       70, 80, 92, 18, 15, 92, 21, 67, 85, 17, 91, 36, 90, 22, 92])

In [5]:
arr4=arr4.reshape(10,10)
arr4

array([[52, 27, 87, 24, 90, 20, 94, 79, 31, 16],
       [91, 86, 21, 40, 65, 35, 33, 99, 26, 43],
       [44, 29, 65, 83, 28, 24, 22, 78, 76, 37],
       [72, 16, 15, 75, 96, 23, 28, 62, 87, 45],
       [86, 18, 85, 36, 64, 72, 18, 83, 39, 58],
       [91, 41, 67, 95, 56, 97, 30, 79, 83, 40],
       [22, 41, 40, 37, 24, 82, 38, 42, 52, 72],
       [98, 53, 23, 47, 49, 25, 38, 30, 40, 86],
       [89, 77, 61, 47, 38, 70, 80, 92, 18, 15],
       [92, 21, 67, 85, 17, 91, 36, 90, 22, 92]])

In [7]:
arr4[2:7,3:7]=100
arr4
# The rows and columns selected by [2:7, 3:7]
# Rows: index 2 to 7 inclusive
# columns index 3 to 6 inclusive

array([[ 52,  27,  87,  24,  90,  20,  94,  79,  31,  16],
       [ 91,  86,  21,  40,  65,  35,  33,  99,  26,  43],
       [ 44,  29,  65, 100, 100, 100, 100,  78,  76,  37],
       [ 72,  16,  15, 100, 100, 100, 100,  62,  87,  45],
       [ 86,  18,  85, 100, 100, 100, 100,  83,  39,  58],
       [ 91,  41,  67, 100, 100, 100, 100,  79,  83,  40],
       [ 22,  41,  40, 100, 100, 100, 100,  42,  52,  72],
       [ 98,  53,  23,  47,  49,  25,  38,  30,  40,  86],
       [ 89,  77,  61,  47,  38,  70,  80,  92,  18,  15],
       [ 92,  21,  67,  85,  17,  91,  36,  90,  22,  92]])

In [8]:
arr4.ndim

2

In [10]:
arr4= arr4.flatten() ## method converts a muti dimensional array into a one dimensional array.
arr4

array([ 52,  27,  87,  24,  90,  20,  94,  79,  31,  16,  91,  86,  21,
        40,  65,  35,  33,  99,  26,  43,  44,  29,  65, 100, 100, 100,
       100,  78,  76,  37,  72,  16,  15, 100, 100, 100, 100,  62,  87,
        45,  86,  18,  85, 100, 100, 100, 100,  83,  39,  58,  91,  41,
        67, 100, 100, 100, 100,  79,  83,  40,  22,  41,  40, 100, 100,
       100, 100,  42,  52,  72,  98,  53,  23,  47,  49,  25,  38,  30,
        40,  86,  89,  77,  61,  47,  38,  70,  80,  92,  18,  15,  92,
        21,  67,  85,  17,  91,  36,  90,  22,  92])

In [11]:
arr4[arr4 == 52]

array([52, 52])

In [12]:
arr4[arr4 != 52]

array([ 27,  87,  24,  90,  20,  94,  79,  31,  16,  91,  86,  21,  40,
        65,  35,  33,  99,  26,  43,  44,  29,  65, 100, 100, 100, 100,
        78,  76,  37,  72,  16,  15, 100, 100, 100, 100,  62,  87,  45,
        86,  18,  85, 100, 100, 100, 100,  83,  39,  58,  91,  41,  67,
       100, 100, 100, 100,  79,  83,  40,  22,  41,  40, 100, 100, 100,
       100,  42,  72,  98,  53,  23,  47,  49,  25,  38,  30,  40,  86,
        89,  77,  61,  47,  38,  70,  80,  92,  18,  15,  92,  21,  67,
        85,  17,  91,  36,  90,  22,  92])

In [13]:
arr4[arr4 > 52]

array([ 87,  90,  94,  79,  91,  86,  65,  99,  65, 100, 100, 100, 100,
        78,  76,  72, 100, 100, 100, 100,  62,  87,  86,  85, 100, 100,
       100, 100,  83,  58,  91,  67, 100, 100, 100, 100,  79,  83, 100,
       100, 100, 100,  72,  98,  53,  86,  89,  77,  61,  70,  80,  92,
        92,  67,  85,  91,  90,  92])

In [14]:
arr4[arr4 < 52]

array([27, 24, 20, 31, 16, 21, 40, 35, 33, 26, 43, 44, 29, 37, 16, 15, 45,
       18, 39, 41, 40, 22, 41, 40, 42, 23, 47, 49, 25, 38, 30, 40, 47, 38,
       18, 15, 21, 17, 36, 22])

In [15]:
np.mean(arr4)

64.13

In [16]:
np.median(arr4)

68.5

In [17]:
np.sum(arr4)

6413

In [18]:
np.min(arr4)

15

In [19]:
np.max(arr4)

100

In [20]:
np.std(arr4)

29.820682420092268

In [21]:
np.var(arr4)

889.2731

In [22]:
np.cos(arr4)

array([-0.16299078, -0.29213881,  0.56975033,  0.42417901, -0.44807362,
        0.40808206,  0.96945937, -0.89597095,  0.91474236, -0.95765948,
       -0.99436746, -0.38369844, -0.54772926, -0.66693806, -0.56245385,
       -0.90369221, -0.01327675,  0.03982088,  0.64691932,  0.5551133 ,
        0.99984331, -0.74805753, -0.56245385,  0.86231887,  0.86231887,
        0.86231887,  0.86231887, -0.85780309,  0.82433133,  0.76541405,
       -0.96725059, -0.95765948, -0.75968791,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.67350716,  0.56975033,  0.52532199,
       -0.38369844,  0.66031671, -0.98437664,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.24954012,  0.26664293,  0.11918014,
       -0.99436746, -0.98733928, -0.5177698 ,  0.86231887,  0.86231887,
        0.86231887,  0.86231887, -0.89597095,  0.24954012, -0.66693806,
       -0.99996083, -0.98733928, -0.66693806,  0.86231887,  0.86231887,
        0.86231887,  0.86231887, -0.39998531, -0.16299078, -0.96

In [25]:
np.percentile(arr4,67)

87.0

In [ ]:
# pip install numpy
# pandas
# matplotlib
# seaborn
# plotly